<?php
/** @var \Laminas\View\Renderer\PhpRenderer $this */

?>
<div class="jumbotron home-block">
    <section id="welcome" class="welcome-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Telegram Бот</h1>
                    <p>Бот блокирует ограничивает пользователя вступившего в группу в действиях до тех пор пока не будет выбран ответ на вопрос заданный ботом!</p>
                </div>
            </div>
        </div>
    </section>
</div>






